"""is_deleted_for_category

Revision ID: 24eb543ed156
Revises: a33697d4b9b2
Create Date: 2026-05-17 17:14:04.939198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24eb543ed156'
down_revision: Union[str, Sequence[str], None] = 'a33697d4b9b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'is_deleted')
    # ### end Alembic commands ###
