"""add_image_url

Revision ID: 2ca0202c3ece
Revises: 1bd3b2fcaa2d
Create Date: 2026-05-17 16:14:50.441430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca0202c3ece'
down_revision: Union[str, Sequence[str], None] = '1bd3b2fcaa2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('threads', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('threads', 'image_url')
    op.drop_column('comments', 'image_url')
    # ### end Alembic commands ###
