"""add_images_for_categories

Revision ID: a33697d4b9b2
Revises: 5eb9f38c2ba7
Create Date: 2026-05-17 16:56:22.437224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a33697d4b9b2'
down_revision: Union[str, Sequence[str], None] = '5eb9f38c2ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'image_url')
    # ### end Alembic commands ###
